inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path, include, re_path, register_converter
from main.views import *
from main.converters import *

register_converter(NegativeIntConverter, 'negint')

app_name = 'main'

urlpatterns = [
    path('main/', show_main, name="show_main"),
    path('main/<int:item_count>', show_main, name="show_main"),
    path('', show_readme, name="show_readme"),
    path('archive/<str:file>', show_archive, name="show_archive"),
    path('statics/', show_statics_list, name="show_statics_list"),
    path('main/create_item', create_item, name="create_item"),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),\
    path('main/change_item', change_item, name="change_item"),
    path('main/change_item/<int:id>&<negint:amount>', change_item, name="change_item"),
    path('main/delete_item', delete_item, name="delete_item"),
    path('main/delete_item/<int:id>', delete_item, name="delete_item"),
    path('register/', register, name="register"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator, URLValidator
from inventory.settings import ALLOWED_FILES
import requests
import re
exts = '|'.join(ALLOWED_FILES)

# Create your models here.
def validate_image_url(value):
    # check url has a downloadable file
    try:
        r = requests.get(value, timeout=1)
    except requests.exceptions.RequestException as e:
        print(e)
        raise ValidationError(u'URL doesn\'t exist or isn\'t available currently.')
    
    print(r.headers['Content-Type'])

    if re.match(f"image/({exts})", r.headers['content-type']) == None:
        raise ValidationError(u'Wrong file type.')

class Item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.PositiveIntegerField()
    description = models.TextField()
    rarity = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    effect = models.TextField()
    image_dir = models.URLField(validators=[URLValidator(), validate_image_url])
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from django.forms.widgets import NumberInput
from main.models import Item

class RangeInput(NumberInput):
    input_type = "range"
    template_name = "range.html"

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "rarity", "effect", "image_dir"]
        widgets = {"rarity": RangeInput(attrs={
            "min": 1,
            "max": 5,
            "oninput": "rarityVal.value = this.value",
            "list": "number"})}

main/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.urls import reverse
from main.models import Item
from main.forms import ItemForm
from inventory.settings import BASE_DIR, ALLOWED_FILES, STATIC_URL, STATIC_ROOT
from random import shuffle
import json
import os
import datetime

# Create your views here.
@login_required(login_url='/login')
def show_main(request, item_count=-1):
    # find lengths
    all_item_count = len(Item.objects.all())
    user_item_count = len(Item.objects.filter(created_by=request.user))

    # Grab items from database
    items = Item.objects.all()

    # randomly select n items from database if item_count >= 0
    indexes = [i.pk for i in items]
    if item_count >= 0:
        shuffle(indexes)
        indexes = indexes[:item_count]
        # filter only the id's chosen, then order by rarity (asc.) and name
        items = items.filter(id__in=indexes)

    items = items.order_by('rarity', 'name')
    
    # process rarity into a string
    # ★☆
    rarity = {}
    for i in items:
        rarity[i.pk] = "★" * i.rarity + "☆" * (5 - i.rarity)
    
    if items:
        last_item = items[len(items)-1].pk
    else:
        last_item = -1

    context = {
        'items': items,
        'all_item_count': all_item_count,
        'user_item_count': user_item_count,
        'item_count': len(items),
        'rarity': rarity,
        'last_item': last_item,
    }

    if 'last_login' in request.COOKIES:
        context['last_login'] = request.COOKIES['last_login']

    return render(request, "main.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()), max_age=10000)
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    
    return render(request, 'login.html', {})

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response




def show_readme(request):
    with open(BASE_DIR/'README.md', 'rb') as f:
        a = f.read().decode()   
    context = {
        'content': a,
        'filename': "main"
    }
    return render(request, "md.html", context)


def show_archive(request, file):
    filename = file
    file = 'archive/' + file
    print(file)
    with open(BASE_DIR / file , 'rb') as f:
        a = f.read().decode()   
    
    context = {
        'content': a,
        'filename': filename
    }
    return render(request, "md.html", context)


def show_statics_list(request):
    statics = json.loads(open(os.path.join(STATIC_ROOT, 'staticfiles.json'), "r").read())['paths']
    static_list = {}

    for i in statics:
        # check static location
        sdir = i.split('/')[0]
        # if admin get out
        if sdir == "admin": continue
        if sdir not in static_list:
            static_list[sdir] = []
        static_list[sdir].append('/'.join(i.split('/')[1:]))

    context = {
        'static_list': static_list
    }
    return render(request, "statics_list.html", context)


@login_required(login_url='/login')
def create_item(request):
    form = ItemForm(request.POST or None, initial={'rarity': 3})

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.created_by = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)


@login_required(login_url='/login')
def change_item(request, id, amount=1):
    items = Item.objects.filter(pk=id)

    if len(items) == 0:
        messages.info(request, 'Item does not exist.')
        return HttpResponseRedirect(reverse('main:show_main'))

    item = items[0]

    if item.amount == 0:
        messages.info(request, 'Cannot decrease amount any further.')
        return HttpResponseRedirect(reverse('main:show_main'))
    else:
        item.amount += amount
        item.save()
        
    return HttpResponseRedirect(reverse('main:show_main'))


@login_required(login_url='/login')
def delete_item(request, id):
    items = Item.objects.filter(pk=id)

    if len(items) == 0:
        messages.info(request, 'Item does not exist.')
        return HttpResponseRedirect(reverse('main:show_main'))

    item = items[0]
    
    if item.created_by == request.user:
        item.delete()
        messages.success(request, 'Successfully deleted item.')
    else:
        messages.info(request, 'Item can only be deleted by creator.')
    

    return HttpResponseRedirect(reverse('main:show_main'))


def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/create_item.html
{% extends 'markdown_base.html' %}
{% load static %}
{% block content %}
{% block meta %}
    <title>Create an item</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'main/images/Pela_Sticker_02.png' %}" >
{% endblock meta %}


<h1>New Item</h1>
<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td colspan="2">
                <a>
                    Fill "Image dir" with the url of the image.<br>
                    Files allowed: .gif, .png, .jpeg, .jpg
                </a>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>


{% endblock %}

main/templates/login.html
{% extends 'markdown_base.html' %}

{% block meta %}
    <title>Login</title>
    <style>
        span.helptext {
            border: 0px;
        }
    </style>
{% endblock meta %}

{% block content %}
<h1>Login</h1>

<form method="POST" action="">
    {% csrf_token %}
    <table>
        <tr>
            <td>Username: </td>
            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
        </tr>
                
        <tr>
            <td>Password: </td>
            <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
        </tr>

        <tr>
            <td></td>
            <td><input class="btn login_btn" type="submit" value="Login"></td>
        </tr>
    </table>
</form>

{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}     
    
Don't have an account yet? <a href="{% url 'main:register' %}"><button>Register Now</button></a>
{% endblock %}

main/templates/main.html
{% extends 'markdown_base.html' %}
{% load static %}
{% load get_item %}

{% block meta %}
    <title>Inventory</title>
	<style>
		span.item_window div img {
			position: relative;
			max-height: 200px;
			max-width: 200px;
			left: 50%;
			top: 50%;
			transform: translate(-50%, -50%);
			transition-duration: .2s;
			margin: 0 auto;
		}

		span.item_window div img:hover {
			scale: 1.2;
			translate: 10% 10%;
			transition-duration: .2s;
		}

		span.item_window {
			width: 200px;
			height: 580px;
			padding: 3px;
			padding-bottom: 2px;
			border: 1px solid var(--color-fg-default) ;
			display: inline-block;
		}

		@keyframes rainbow { 
    		to{background-position:1000px 50%}
		}

		.rainbow-text {
			background-image: repeating-linear-gradient( to right,
				rgba(255, 0, 0, 1) 0%,
				rgba(255, 154, 0, 1) 10%,
				rgba(208, 222, 33, 1) 20%,
				rgba(79, 220, 74, 1) 30%,
				rgba(63, 218, 216, 1) 40%,
				rgba(47, 201, 226, 1) 50%,
				rgba(28, 127, 238, 1) 60%,
				rgba(95, 21, 242, 1) 70%,
				rgba(186, 12, 248, 1) 80%,
				rgba(251, 7, 217, 1) 90%,
				rgba(255, 0, 0, 1) 100%);
			text-align: center;
			background-size: 1000px 100px;
			background-clip: text;
			-webkit-background-clip: text;
			-webkit-text-fill-color: rgba(255,255,255,0.2);
			animation: rainbow 6s linear infinite;
		}
	</style>
{% endblock meta %}

{% block content %}
<link rel="shortcut icon" type="image/png" href="{% static 'main/images/March_7th_Sticker_07.png' %}" >


<h1>hsr inventory</h1>


{% if all_item_count == item_count %}
	<h4>There are currently {{all_item_count}} items in this app<br>
		You have created {{user_item_count}} items.<br>
	{% if all_item_count != 0 %}
	To show only n items, append '/{n}' to the url path.<br>
	Example: <a href="10">10 items</a></h4>
	{%endif%}
{%else%}
	<h4>There are currently {{all_item_count}} items in this app, of which {{item_count}} are shown.<br>
	<a href=".">
		<button style="margin-top: 2px;"> See all items </button>
	</a></h4>
{%endif%}

{% if messages %}
	<h4>Messages:</h4>
	{% for message in messages %}  
		<li>{{ message }}</li>  
	{% endfor %}
{% endif %}



<br>

{% for x in items %}
<span class="item_window">
	{% if x.id == 2 %} <a href="{% static 'main/images/tricksnack.gif' %}"> {% endif %}
	
	<div style="padding-bottom: 2px;height:200px;position: relative;background-image:url('/static/main/images/Background_Item_{{x.rarity}}_Star.png');background-size: contain;">
		<img style="background: transparent;" src="{{ x.image_dir }}" alt="{{x.name}}" title="{{x.name}}" width="160" class="bound"/><br>
	</div>
	<div style="border-bottom:1px solid var(--color-border-default);height:180px;">
		<b {% if x.pk == last_item %} class="rainbow-text" {% endif %} >
			{{x.name}}
			{% if x.pk == 2 and x.name == "Trick Snack" %} </a> {% endif %}
			
			<br>({{ rarity|get_item:x.pk }})
		</b>
		<br>
		Amount: {{x.amount}}
		<a href="{% url 'main:change_item' id=x.pk amount=1 %}">
			<button> + </button>
		</a>
		<a href="{% url 'main:change_item' id=x.pk amount=-1 %}">
			<button> - </button>
		</a>
		<br>
		Created by: {{ x.created_by.username }}
		<br>
		<a href="{% url 'main:delete_item'  id=x.pk %}" >
			<button style="background-color: red; color:black;">
				Delete Item
			</button>
		</a>
	</div>
	<div style="height:200px;width:200px;overflow:auto;">
		{{x.description}}<br>
		Effect: {{x.effect}}<br><br>
	</div>
</span>
{% endfor %}


<br><br>
<a href="{% url 'main:create_item' %}">
	<button style="margin-bottom: 4px;">
		Add New Item
	</button>
</a>
<br>

<a href=".."><button>Go back</button></a>

<br>
{% if last_login %}
<h4>Last login: {{last_login}}</h4>
{% endif %}

<hr>
description, effects, and images taken (and condensed) from <a href=https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki>Honkai: Star Rail wiki</a>.<br>
github-markdown.css by <a href="https://github.com/sindresorhus/github-markdown-css">sindresorhus</a><br>
bootstrap.min.css by <a href="https://github.com/twbs/bootstrap/">The Bootstrap Authors</a><br>
both css stylesheets modified and used under the MIT license.<br>
website by sefriano edsel jieftara, class of pbp d


{% endblock content %}

main/templates/markdown_base.html
{% load static %}
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/github-markdown.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">
	<style>
		.markdown-body {
			box-sizing: border-box;
			min-width: 200px;
			max-width: 1200px;
			margin: 0 auto;
			padding: 45px;
			padding-top: 20px;
			z-index: -50;
		}

		.dropdown {
			display: inline-block;
			padding-left: calc(var(--bs-gutter-x) * .5);
			margin-right: auto;
			margin-left: auto;
		}

		.dropdown img.icon_dark,
		.dropdown img.icon_light {
			height: 50px !important;
			width: 42px !important;
			margin-left: 1rem;
			position: relative;
			background-color: #2b3035;
			z-index: 2;
		}

		.dropdown-content {
			display: block;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			padding: 12px 16px;
			
			transform: translateY(-100%);
			animation-timing-function: ease-in-out;
			transition-duration: .3s;
		}
		
		.dropdown>.dropdown-content:hover,
		.dropdown>img:focus ~ .dropdown-content,
		.dropdown>img:hover ~ .dropdown-content{
  			display: block;
			transform: translateY(0%);
			animation-timing-function: ease-in-out;
			transition-duration: .3s;
		}

		@media (max-width: 767px) {
			.markdown-body {
				padding: 15px;
			}
		}

		@media (prefers-color-scheme: dark) {
			body {
				background-color: #0d1117;
			}
			.dropdown .icon_light {
				display: none;
			}
			.dropdown-content {
				background-color: #2b3035;
			}
		}

		@media (prefers-color-scheme: light) {
			.dropdown .icon_dark {
				display: none;
			}
		}
	</style>
	{% block meta %}
	{% endblock meta %}
</head>

<body>
	<nav class="navbar navbar-expand-lg bg-body-tertiary" style="padding-right: 12%; margin-bottom: 20px;">
		<div class="dropdown" style="margin-left: 0;">
			<img class="icon_dark" tabindex="0" src="{% static 'main/icons/Menu_icon_dark.png'%}">
			<img class="icon_light" tabindex="0" src="{% static 'main/icons/Menu_icon_light.png'%}">
			<ul class="navbar-nav dropdown-content">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" tabindex="-1" href="{% url 'main:show_main' %}">
						Main page
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" tabindex="-1" href="{% url 'main:create_item' %}">
						Add item
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" tabindex="-1" href="{% url 'main:show_statics_list' %}">
						Statics
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" tabindex="-1" href="/archive/archive_list.md">
						Archive
					</a>
				</li>
			</ul>
		</div>
		
		<div class="container-fluid">
			<a class="navbar-brand" href="/" style="z-index: 2;">
				hsr inventory
			</a>
			<div class="collapse navbar-collapse" id="navbarNav">
				<span id="user-information" style="margin-left: auto;">
					<span class="navbar-text" style="margin-right: 5px;">
					{% if not request.user.is_anonymous %}
						Hello, {{ request.user.username }}!
					{% else %}
						Hello user, please log in.
					{% endif%}
					</span>
					{% if not request.user.is_anonymous %}
						<a href="{% url 'main:logout' %}">
							<button class="login-button">
								Logout
							</button>
						</a>
					{% else %}
						<a href="{% url 'main:login' %}">
							<button class="login-button">
								Login
							</button>
						</a>
					{% endif%}
				</span>
			</div> 
		</div>
	</nav>

	<article class="markdown-body">
	{% block content %}
	{% endblock content %}
	</article>
</body>

main/templates/md.html
{% extends 'markdown_base.html' %}
{% load static %}
{% load markdown_extras %}

{% block meta %}
<title>{{filename}}</title>
{% endblock meta %}

{% block content %}
{{ content | markdown | safe }}
{% endblock %}

main/templates/media.html
{% load static %}
{% load markdown_extras %}

<link rel="shortcut icon" type="image/png" href="{% static 'main/media/Pela_Sticker_02.png' %}" >
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'main/css/github-markdown.css' %}">
<style>
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 1080px;
		margin: 0 auto;
		padding: 45px;
	}

	@media (max-width: 767px) {
		.markdown-body {
			padding: 15px;
		}
	}
	@media (prefers-color-scheme: dark) {
		body {
			background-color: #0d1117;
		}
	}
</style>

<article class="markdown-body">
<h2>Media list:</h2>

{% for media in media_list %}
<a href="{{media}}">{{media}}</a><br>
{% endfor %}
<hr>
</article>

main/templates/range.html
<input type="{{ widget.type }}" name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>
<text><output id="rarityVal">
    {% if widget.value != None %}
        {{widget.value|stringformat:'s'}}
    {%else%}
        3
    {%endif%}</output> stars</text><br>
<datalist id="number">
    <option>1</option>
    <option>2</option>
    <option>3</option>
    <option>4</option>
    <option>5</option>
</datalist>

main/templates/register.html
{% extends 'markdown_base.html' %}

{% block meta %}
    <title>Register</title>
    <style>
        span.helptext {
            border: 0px;
        }
    </style>
{% endblock meta %}

{% block content %}
<h1>Register</h1>

<form method="POST" >  
    {% csrf_token %}  
    <table>  
        {{ form.as_table }}  
        <tr>  
            <td></td>
            <td><input type="submit" name="submit" value="Register"/></td>  
        </tr>  
    </table>  
</form>

{% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
{% endif %}

{% endblock content %}

main/templates/statics_list.html
{% extends 'markdown_base.html' %}
{% load static %}
{% load get_item %}

{% block meta %}
	<link rel="shortcut icon" type="image/png" href="{% static 'main/images/Pela_Sticker_02.png' %}" >
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Static list</title>
{% endblock meta %}


{% block content %}
<h2>Static files list:</h2>

{% for sdir in static_list.keys %}
	<h4>{{sdir}}/</h4>
	{% for statics in static_list|get_item:sdir %}
		<li><a href="{% static sdir|add:'/'|add:statics %}">{{statics}}</a></li>
	{% endfor %}
{% endfor %}

{% endblock content %}